use axum::Router;
use coaxial::{
    attrs,
    context::Context,
    family::Family,
    html::{
        b, button, div, p, style, Component, Content, ContentValue, Element, Mut, Renderable, State,
    },
    live::live,
    CoaxialResponse,
};

// closures get a Counter<MutFamily>

// actual code

struct CounterComponent {
    counter: i32,
    other: u32,
}

impl CounterComponent {
    pub fn new() -> Self {
        Self {
            counter: 0,
            other: 0,
        }
    }
}

// TODO generated by macro
impl Component for CounterComponent {
    type Component<FAM: Family> = CounterComponentGeneric<FAM>;

    type Message = Message;

    fn make_generic<FAM: Family>(self) -> Self::Component<FAM> {
        Self::Component {
            counter: FAM::from(self.counter),
            other: FAM::from(self.other),
        }
    }
}

// TODO generated by macro
struct CounterComponentGeneric<FAM: Family> {
    counter: FAM::This<i32>,
    other: FAM::This<u32>,
}

// so the ugly thing about this is that it can't be called self
// tho it technically is. i could call the param component and be done with that, but like...
impl Renderable for CounterComponent {
    fn render(component: &State<Self>) -> Element {
        div(
            Content::List(vec![
                p(
                    Content::List(vec![b(component.counter, Default::default()).into()]),
                    Default::default(),
                )
                .into(),
                // button("update", attrs!("onclick" => &update)).into(),
                button(
                    "update",
                    // TODO we need to use format cause message can't be converted to attribute
                    attrs!("onclick" => format!("{:?}", Message::PlusOne)),
                )
                .into(),
            ]),
            Default::default(),
        )
    }
}

#[derive(Debug)]
enum Message {
    PlusOne,
    MinusOne,
}

impl coaxial::html::Message<CounterComponent> for Message {
    fn handle(&self, component: &mut Mut<CounterComponent>) {
        match &self {
            Message::PlusOne => *component.counter += 1,
            Message::MinusOne => *component.counter -= 1,
        }
    }
}

// TODO maybe we try to make normal functions work?
fn update(component: &mut Mut<CounterComponent>) {
    *component.counter += 1;
}

async fn counter(mut ctx: Context) -> CoaxialResponse {
    let counter = ctx.use_state(0i32);

    let counter_plus_1 = ctx.use_computed(counter, |counter| *counter + 1);

    let update = ctx.use_closure(move || async move {
        counter.set(*counter.get() + 1);
    });

    ctx.with(div(
        Content::List(vec![
            style(
                ContentValue::Raw(
                    html_escape::encode_style(include_str!("styles.css")).to_string(),
                ),
                Default::default(),
            )
            .into(),
            p(
                Content::List(vec![
                    b(counter, Default::default()).into(),
                    " + 1 = ".into(),
                    b(counter_plus_1, Default::default()).into(),
                ]),
                Default::default(),
            )
            .into(),
            button("update", attrs!("onclick" => update)).into(),
        ]),
        Default::default(),
    ))
}

#[tokio::main]
async fn main() {
    let app = Router::new().route("/", live(counter));

    let listener = tokio::net::TcpListener::bind("0.0.0.0:3000").await.unwrap();
    axum::serve(listener, app).await.unwrap();
}
